name: monlab-escalation
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'null'
      group_by: [alertname, cluster, namespace]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        # critical -> page (fast repeat) and also continue to ticketing
        - matchers: ['severity="critical"']
          receiver: page
          group_wait: 10s
          repeat_interval: 1h
          continue: true
        # warning -> ticket
        - matchers: ['severity="warning"']
          receiver: ticket
        # info -> swallow
        - matchers: ['severity="info"']
          receiver: 'null'
    receivers:
      - name: 'null'
      - name: page
        pagerduty_configs:
          - routing_key: CHANGEME-pagerduty-routing-key
            send_resolved: true
      - name: ticket
        slack_configs:
          - api_url: https://hooks.slack.com/services/CHANGEME
            channel: '#alerts'
            send_resolved: true
  templates: {}
