name: default
prometheus:
  render: mimirtool
grafana:
  render: grizzly
mixins:
  base:
    config:
      mimirNamespace: base
      grafanaDashboardFolder: Base
      serverLinuxLink: '/d/dashboardlink'
      baseClusterLink: '/d/dashboardlink'
    source:
      directory:
        path: /mixins/base-mixin
  node:
    config:
      mimirNamespace: node
      grafanaDashboardFolder: Platform
    source:
      git:
        url: https://github.com/prometheus/node_exporter.git
        ref: master
        depth: 1
      includePaths:
        - docs/node-mixin/**/*
      newRootPath: docs/node-mixin
  windows:
    config:
      mimirNamespace: windows
      grafanaDashboardFolder: Base
    source:
      git:
        url: https://github.com/grafana/jsonnet-libs.git
        ref: master
        depth: 1
      includePaths:
        - windows-mixin/**/*
      newRootPath: windows-mixin
libs:
  windows-observ-lib:
    source:
      git:
        url: https://github.com/grafana/jsonnet-libs.git
        ref: master
        depth: 1
      includePaths:
        - windows-observ-lib/**/*
      newRootPath: windows-observ-lib
dashboards:
  pyroscope-overview:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/main/pyroscope-mixin/pyroscope-overview.json
        sha256: 72c6d410677101f3317f74473930b17dd76e77a8c578c4d81e7e189f820c5a0b
    config:
      grafanaDashboardFolder: Monitoring
      uid: pyroscope-overview
  kspan-overview:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/main/kspan-mixin/kspan-overview.json
        sha256: 1f2924784316f5ef96cf3ec6698c9168990bc9e19a2f3582ecccc70436e17b6e
    config:
      grafanaDashboardFolder: Monitoring
      uid: kspan-overview
  kspan-deployments:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/main/kspan-mixin/kspan-deployments.json
        sha256: 0d8c34ae62252a3eaace636e9ec543e67b65df8ff46ab550e53ff7fa7850ed38
    config:
      grafanaDashboardFolder: Monitoring
      uid: kspan-deployments
  backstage-app-graph:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/main/backstage-mixin/backstage-app-graph.json
        sha256: 8f679ddf3617a87861234f956572ee7edfd62cc7b9d64e0de8061fc9cdd08cd9
    config:
      grafanaDashboardFolder: Platform
      uid: backstage-app-graph
