name: k8s-monitoring
prometheus:
  render: mimirtool
grafana:
  render: grizzly
mixins:
  alloy:
    config:
      mimirNamespace: alloy
      grafanaDashboardFolder: Monitoring
    source:
      git:
        url: https://github.com/grafana/alloy.git
        ref: main
        depth: 1
      includePaths:
        - operations/alloy-mixin/**/*
      newRootPath: operations/alloy-mixin
  cert-manager:
    config:
      mimirNamespace: cert-manager
      enableMultiCluster: true
      grafanaDashboardFolder: Platform
    source:
      git:
        url: https://github.com/imusmanmalik/cert-manager-mixin.git
        ref: main
        depth: 1
  ingress-nginx:
    config:
      mimirNamespace: ingress-nginx
      grafanaDashboardFolder: Platform
    source:
      git:
        url: https://github.com/adinhodovic/ingress-nginx-mixin.git
        ref: main
        depth: 1
  kube-state-metrics:
    config:
      mimirNamespace: kube-state-metrics
      grafanaDashboardFolder: Monitoring
    source:
      git:
        url: https://github.com/kubernetes/kube-state-metrics.git
        ref: main
        depth: 1
      includePaths:
        - jsonnet/kube-state-metrics-mixin//**/*
      newRootPath: jsonnet/kube-state-metrics-mixin
  kubernetes-events:
    config:
      mimirNamespace: kubernetes-events
      grafanaDashboardFolder: Platform
      lokiRuleGroups:
        - kubernetes-events.rules
    source:
      git:
        url: https://github.com/adinhodovic/kubernetes-events-mixin.git
        ref: main
        depth: 1
  kubernetes:
    mixinDir: /source/mixins/kubernetes-mixin
    vendorDir: /source/mixins/kubernetes-mixin/vendor
    config:
      showMultiCluster: true
      mimirNamespace: kubernetes
      grafanaDashboardFolder: Platform
      cadvisorSelector: job="integrations/kubernetes/cadvisor"
      kubeletSelector: job="integrations/kubernetes/kubelet"
      kubeApiserverSelector: job="integrations/kubernetes/kube-apiserver"
      kubeProxySelector: job="integrations/kubernetes/kube-proxy"
      kubeStateMetricsSelector: job="integrations/kubernetes/kube-state-metrics"
      nodeExporterSelector: job="integrations/node_exporter"
    source:
      git:
        url: https://github.com/kubernetes-monitoring/kubernetes-mixin.git
        ref: master
        depth: 1
  opencost:
    config:
      mimirNamespace: opencost
      grafanaDashboardFolder: Monitoring
    source:
      git:
        url: https://github.com/adinhodovic/opencost-mixin.git
        ref: main
        depth: 1
  loki:
    config:
      mimirNamespace: loki
      grafanaDashboardFolder: Monitoring
    source:
      git: {url: https://github.com/grafana/loki.git, ref: main, depth: 1}
      includePaths: [production/loki-mixin/**/*]
      newRootPath: production/loki-mixin
  mimir:
    config:
      mimirNamespace: mimir
      grafanaDashboardFolder: Monitoring
    source:
      git: {url: https://github.com/grafana/mimir.git, ref: main, depth: 1}
      includePaths: [operations/mimir-mixin/**/*]
      newRootPath: operations/mimir-mixin
  tempo:
    config:
      mimirNamespace: tempo
      grafanaDashboardFolder: Monitoring
    source:
      git: {url: https://github.com/grafana/tempo.git, ref: main, depth: 1}
      includePaths: [operations/tempo-mixin/**/*]
      newRootPath: operations/tempo-mixin
  node-exporter:
    config:
      mimirNamespace: node-exporter
      grafanaDashboardFolder: Monitoring
      nodeExporterSelector: job="integrations/node_exporter"
    source:
      git: {url: https://github.com/prometheus/node_exporter.git, ref: master, depth: 1}
      includePaths: [docs/node-mixin/**/*]
      newRootPath: docs/node-mixin
  alertmanager:
    config:
      mimirNamespace: alertmanager
      grafanaDashboardFolder: Monitoring
    source:
      git: {url: https://github.com/prometheus/alertmanager.git, ref: main, depth: 1}
      includePaths: [doc/alertmanager-mixin/**/*]
      newRootPath: doc/alertmanager-mixin
dashboards:
  kubernetes-views-global:
    source:
      grafana:
        id: 15757
        revision: 43
    config:
      grafanaDashboardFolder: Platform
      uid: kubernetes-views-global
      datasources:
        DS_PROMETHEUS: global-monitor-mimir-server
  k8s-node-metrics-multi-clusters:
    source:
      grafana:
        id: 22413
        revision: 6
    config:
      grafanaDashboardFolder: Platform
      uid: k8s-node-metrics-multi-clusters
  k8s-dashboard-en:
    source:
      grafana:
        id: 15661
        revision: 2
    config:
      grafanaDashboardFolder: Platform
      uid: k8s-dashboard-en
      datasources:
        DS__VICTORIAMETRICS-PROD-ALL: global-monitor-mimir-server
  sloth-slo-detail:
    source:
      grafana: {id: 14348, revision: 2}
    config:
      grafanaDashboardFolder: Monitoring
      uid: sloth-slo-detail
      datasources:
        DS_PROMETHEUS: global-monitor-mimir-server
  sloth-high-level-slos:
    source:
      grafana: {id: 14643, revision: 1}
    config:
      grafanaDashboardFolder: Monitoring
      uid: sloth-high-level-slos
      datasources:
        DS_PROMETHEUS: global-monitor-mimir-server
  pyroscope-overview:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/feat/prometheus-configmap-render/pyroscope-mixin/pyroscope-overview.json
        sha256: 72c6d410677101f3317f74473930b17dd76e77a8c578c4d81e7e189f820c5a0b
    config:
      grafanaDashboardFolder: Monitoring
      uid: pyroscope-overview
  kspan-overview:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/feat/prometheus-configmap-render/kspan-mixin/kspan-overview.json
        sha256: 1f2924784316f5ef96cf3ec6698c9168990bc9e19a2f3582ecccc70436e17b6e
    config:
      grafanaDashboardFolder: Monitoring
      uid: kspan-overview
  kspan-deployments:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/feat/prometheus-configmap-render/kspan-mixin/kspan-deployments.json
        sha256: 0d8c34ae62252a3eaace636e9ec543e67b65df8ff46ab550e53ff7fa7850ed38
    config:
      grafanaDashboardFolder: Monitoring
      uid: kspan-deployments
  backstage-app-graph:
    source:
      http:
        url: https://raw.githubusercontent.com/cznewt/monitor-tools/feat/prometheus-configmap-render/backstage-mixin/backstage-app-graph.json
        sha256: 8f679ddf3617a87861234f956572ee7edfd62cc7b9d64e0de8061fc9cdd08cd9
    config:
      grafanaDashboardFolder: Platform
      uid: backstage-app-graph
