#!/bin/bash

BUILD_DIR="${BUILD_DIR:=/build/default/mimirtool/mimir-rules}"

yaml_files=$(find "$BUILD_DIR" -maxdepth 1 -type f -name "*.yaml")

if [ -z "$yaml_files" ]; then echo "No *.yaml files found in '$BUILD_DIR'."; exit 1; fi

mkdir -p "$BUILD_DIR/metrics"

for yaml_file in $yaml_files; do
  echo "Analysing mimirtool MimirRules $yaml_file..."
  filename=$(basename "$yaml_file")
  plain_name="${filename%.*}"
  mimirtool analyze rule-file $yaml_file --output="$BUILD_DIR/metrics/$plain_name.json"
done
