#!/bin/bash

BUILD_DIR="${BUILD_DIR:=/build/default/plain/grafana-dashboards}"

json_files=$(find "$BUILD_DIR" -maxdepth 1 -type f -name "*.json")

if [ -z "$json_files" ]; then echo "No *.json files found in '$BUILD_DIR'."; exit 1; fi

mkdir -p "$BUILD_DIR/metrics"

for json_file in $json_files; do
  echo "Analysing plain GrafanaDashobards $json_file..."
  filename=$(basename "$json_file")
  plain_name="${filename%.*}"
  mimirtool analyze dashboard $json_file --output="$BUILD_DIR/metrics/$plain_name.json"
done