#!/bin/bash

CONFIG_FILE="${CONFIG_FILE:=/config/default.yaml}"
VENDOR_DIR="/scripts/vendor"

ENV_NAME=$(yq eval ".name" "$CONFIG_FILE")
grafana=$(yq eval ".grafana.render" "$CONFIG_FILE")
prometheus=$(yq eval ".prometheus.render" "$CONFIG_FILE")
loki=$(yq eval ".loki.render" "$CONFIG_FILE")
alertmanager=$(yq eval ".alertmanager.render" "$CONFIG_FILE")

# grafana resources
printf "\nApplying Grafana resources with $grafana processor...\n"

if [ "$grafana" = "grizzly" ]; then 
  CONFIG_FILE=$CONFIG_FILE BUILD_DIR=/build/$ENV_NAME/grizzly/grafana-folders apply-grizzly-grafana-folders
  CONFIG_FILE=$CONFIG_FILE BUILD_DIR=/build/$ENV_NAME/grizzly/grafana-dashboards apply-grizzly-grafana-dashboards
fi

# prometheus resources
printf  "\nApplying Prometheus resources with $prometheus processor...\n"
if [ "$prometheus" = "mimirtool" ]; then
  CONFIG_FILE=$CONFIG_FILE BUILD_DIR=/build/$ENV_NAME/mimirtool/mimir-rules apply-mimirtool-mimir-rules
fi

# loki resources
printf  "\nApplying Loki resources with $loki processor...\n"
if [ "$loki" = "lokitool" ]; then
  CONFIG_FILE=$CONFIG_FILE BUILD_DIR=/build/$ENV_NAME/lokitool/loki-rules apply-lokitool-loki-rules
fi

# alertmanager resources
printf  "\nApplying Alertmanager resources with $alertmanager processor...\n"

if [ "$alertnamanger" = "mimirtool" ]; then 
  CONFIG_FILE=$CONFIG_FILE BUILD_DIR=/build/$ENV_NAME/mimirtool/alertmanager-config apply-mimirtool-alertmanager-config
fi
