#!/bin/bash

BUILD_DIR="${BUILD_DIR:=/build/default/mimirtool/mimir-rules}"

yaml_files=$(find "$BUILD_DIR" -maxdepth 1 -type f -name "*.yaml")

if [ -z "$yaml_files" ]; then echo "No *.yaml files found in '$BUILD_DIR'."; exit 1; fi

if [ -z "$MIMIR_ADDRESS" ]; then echo "MIMIR_ADDRESS not set, cannot connect to Mimir server."; exit 1; fi
if [ -z "$MIMIR_TENANT_ID" ]; then echo "MIMIR_TENANT_ID not set, cannot connect to Mimir server."; exit 1; fi

for yaml_file in $yaml_files; do
  echo "Applying $yaml_file mimirtool MimirRules to $MIMIR_ADDRESS/$MIMIR_TENANT_ID"
  mimirtool rules load "$yaml_file"
done
