#!/bin/bash

CONFIG_FILE="${CONFIG_FILE:=/config/default.yaml}"
VENDOR_DIR="/scripts/vendor"
SOURCE_DIR="${SOURCE_DIR:=/source/default}"

if [ ! -f "$CONFIG_FILE" ]; then echo "Error: Config file $CONFIG_FILE does not exist."; exit 1; fi
keys=$(yq eval '.mixins | keys' "$CONFIG_FILE" | grep -v '^\[' | grep -v '^\]' | awk '{$1=$1};1')

for key in $keys; do
  if [ "$key" = "-" ]; then continue; fi
  if [ -f "$SOURCE_DIR/mixins/$key-mixin/jsonnetfile.json" ]; then
      echo "Installing $SOURCE_DIR/mixins/$key-mixin/jsonnetfile.json dependencies..."
      cd $SOURCE_DIR/mixins/$key-mixin
      jb install
  else
      echo "No dependencies for $SOURCE_DIR/mixins/$key-mixin/."
  fi
done

cd ~