#!/bin/bash

BUILD_DIR="${BUILD_DIR:=/build/default/plain/grafana-dashboards}"

json_files=$(find "$BUILD_DIR" -maxdepth 1 -type f -name "*.json")

if [ -z "$json_files" ]; then echo "No *.json files found in '$BUILD_DIR'."; exit 1; fi

for json_file in $json_files; do
  echo "Linting plain GrafanaDashobard $json_file..."
  dashboard-linter lint $json_file
done
