#!/bin/bash

CONFIG_FILE="${CONFIG_FILE:=/config/default.yaml}"
VENDOR_DIR="/scripts/vendor"
BUILD_DIR="${BUILD_DIR:=/source/default/pyrra/pyrra-slos}"

if [ ! -f "$CONFIG_FILE" ]; then echo "Error: Config file $CONFIG_FILE does not exist."; exit 1; fi
pyrra=$(yq eval '.pyrra.slos | keys' "$CONFIG_FILE" | grep -v '^\[' | grep -v '^\]' | awk '{$1=$1};1')

if [ "$pyrra" = "null" ] || [ -z "$pyrra" ]; then
    echo "No pyrra in $CONFIG_FILE config."
    exit 0
else
    echo "Rendering pyrra ServiceLevelObjective(s) to $BUILD_DIR..."
    jsonnet -c -S -m $BUILD_DIR -J $VENDOR_DIR \
      -e "(import 'cbm.libsonnet').pyrraRules(std.parseYaml(importstr '$CONFIG_FILE'))"
fi
