#!/bin/bash

CONFIG_FILE="${CONFIG_FILE:=/config/default.yaml}"
VENDOR_DIR="/scripts/vendor"
SOURCE_DIR="${SOURCE_DIR:=/source/default}"
BUILD_DIR="${BUILD_DIR:=/build/default/grizzly/grafana-folders}"

if [ ! -f "$CONFIG_FILE" ]; then echo "Error: Config file $CONFIG_FILE does not exist."; exit 1; fi
keys=$(yq eval -o=json -I=0 '.mixins | keys' "$CONFIG_FILE" 2>/dev/null | jq -r '.[]?')

for key in $keys; do
  if [ "$key" = "-" ]; then continue; fi
  mixinDir="$SOURCE_DIR/mixins/$key-mixin"
  echo "Rendering $mixinDir grizzly GrafanaFolders to $BUILD_DIR..."
  jsonnet -c -S -m $BUILD_DIR -J $VENDOR_DIR \
  -e "(import 'cbm.libsonnet').grizzlyGrafanaFolders('$key', (import '$mixinDir/mixin.libsonnet'), std.parseYaml(importstr '$CONFIG_FILE'))"
done

dashboards=$(yq eval -o=json -I=0 '.dashboards | keys' "$CONFIG_FILE" 2>/dev/null | jq -r '.[]?')

if [ -n "$dashboards" ]; then
  for key in $dashboards; do
    if [ -z "$key" ]; then continue; fi
    folder=$(yq eval ".dashboards.\"${key}\".config.grafanaDashboardFolder" "$CONFIG_FILE")
    if [ "$folder" = "null" ] || [ -z "$folder" ]; then continue; fi
    echo "Rendering dashboard '$key' grizzly GrafanaFolder to $BUILD_DIR..."
    jsonnet -c -S -m $BUILD_DIR -J $VENDOR_DIR \
      -e "(import 'cbm.libsonnet').grizzlyDashboardFolders('$key', std.parseYaml(importstr '$CONFIG_FILE'))"
  done
fi
