#!/bin/bash

cd /source

mkdir -p /source/out/prometheus_alerts

jsonnet -c -S -J "/source/vendor" \
  -e "std.manifestYamlDoc((import 'mixin.libsonnet').prometheusAlerts)" > /source/out/prometheus_alerts/alerts.yaml
