#!/bin/bash

CONFIG_FILE="${CONFIG_FILE:=/config/default.yaml}"
VENDOR_DIR="/scripts/vendor"
SOURCE_DIR="${SOURCE_DIR:=/source/default}"
BUILD_DIR="${BUILD_DIR:=/build/default/grizzly/grafana-datasources}"

grafana=$(yq eval -o=json -I=0 '.grafana.datasources | keys' "$CONFIG_FILE" 2>/dev/null | jq -r '.[]?')

if [ "$grafana" = "null" ] || [ -z "$grafana" ]; then
    echo "No grafana defined in $CONFIG_FILE config."
    exit 0
else
    echo "Rendering mimirtool GrafanaDatasource to $BUILD_DIR..."
    jsonnet -c -S -m $BUILD_DIR -J $VENDOR_DIR -e \
      "(import 'cb.libsonnet').grizzly.grafanaDatasources(std.parseYaml(importstr '$CONFIG_FILE'))"
fi
