#!/bin/bash

CONFIG_FILE="${CONFIG_FILE:=/config/default.yaml}"

if [ ! -f "$CONFIG_FILE" ]; then echo "Error: Config file $CONFIG_FILE does not exist."; exit 1; fi
mixins=$(yq eval -o=json -I=0 '.mixins | keys' "$CONFIG_FILE" 2>/dev/null | jq -r '.[]?')
libs=$(yq eval -o=json -I=0 '.libs | keys' "$CONFIG_FILE" 2>/dev/null | jq -r '.[]?')

if [ "$mixins" = "null" ] || [ -z "$mixins" ]; then echo "No mixins found."; else
  echo "Rendering vendir MixinConfig to $BUILD_DIR..."
fi

if [ "$libs" = "null" ] || [ -z "$libs" ]; then echo "No libs found."; else
  echo "Rendering vendir LibConfig to $BUILD_DIR..."
fi
