{{- if and (not .Values.existingSecret) .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitor-tools.fullname" . }}-env
  labels:
    {{- include "monitor-tools.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
