name: Build monitor-tools

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
    paths:
      - docker/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cznewton/monitor-tools

jobs:
  build-monitor-tools:
    name: "Build monitor-tools"
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      APP_NAME: monitor-tools
      APP_DIR: docker
